// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZbJ_yKb0O2KMkDAgGRan8kIQOJ7kLS0',
    appId: '1:892440916635:web:3093a2ade77a7187324c3e',
    messagingSenderId: '892440916635',
    projectId: 'expense-tracker-d2235',
    authDomain: 'expense-tracker-d2235.firebaseapp.com',
    storageBucket: 'expense-tracker-d2235.firebasestorage.app',
    measurementId: 'G-NGTE4QMCJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZSPWW0stYIpE5WKNiI60MO_sSyPKosBw',
    appId: '1:892440916635:android:1ed47cd91030d970324c3e',
    messagingSenderId: '892440916635',
    projectId: 'expense-tracker-d2235',
    storageBucket: 'expense-tracker-d2235.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrZbJ_yKb0O2KMkDAgGRan8kIQOJ7kLS0',
    appId: '1:892440916635:web:7919a41cd781c8df324c3e',
    messagingSenderId: '892440916635',
    projectId: 'expense-tracker-d2235',
    authDomain: 'expense-tracker-d2235.firebaseapp.com',
    storageBucket: 'expense-tracker-d2235.firebasestorage.app',
    measurementId: 'G-3V6LDWK5FS',
  );
}
